/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITicTacToe, ITicTacToeInterface } from "../ITicTacToe";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes2",
        name: "tableX",
        type: "bytes2",
      },
      {
        indexed: false,
        internalType: "bytes2",
        name: "tableO",
        type: "bytes2",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "betAmount",
        type: "uint256",
      },
    ],
    name: "Loser",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "penaltyPlayer",
        type: "address",
      },
    ],
    name: "Overtime",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "Restart",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "column",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "row",
        type: "uint8",
      },
    ],
    name: "Select",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes2",
        name: "tableX",
        type: "bytes2",
      },
      {
        indexed: false,
        internalType: "bytes2",
        name: "table0",
        type: "bytes2",
      },
    ],
    name: "Tie",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes2",
        name: "tableX",
        type: "bytes2",
      },
      {
        indexed: false,
        internalType: "bytes2",
        name: "tableO",
        type: "bytes2",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "betAmount",
        type: "uint256",
      },
    ],
    name: "Winner",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "player",
        type: "uint8",
      },
    ],
    name: "getTable",
    outputs: [
      {
        internalType: "bytes2",
        name: "",
        type: "bytes2",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "column",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "row",
        type: "uint8",
      },
    ],
    name: "select",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITicTacToe__factory {
  static readonly abi = _abi;
  static createInterface(): ITicTacToeInterface {
    return new utils.Interface(_abi) as ITicTacToeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITicTacToe {
    return new Contract(address, _abi, signerOrProvider) as ITicTacToe;
  }
}
