/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITicTacToe } from "./ITicTacToe";
export type { TicTacToe } from "./TicTacToe";

export { ITicTacToe__factory } from "./factories/ITicTacToe__factory";
export { TicTacToe__factory } from "./factories/TicTacToe__factory";
